services:
  rchan3-dev:
    build: .
    restart: always
    working_dir: '/workspace'
    tty: true
    volumes:
      - type: bind
        source: ../
        target: /workspace
    environment:
      TZ: Asia/Tokyo
